Verify that we catch the return code of Exit
