Verify we catch the exit code of return
